# -*- coding: utf-8 -*-
"""Algorytmy29102023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O65CL7lAhFamvgMwRsfH8T5NNsC_yf1U
"""

import time

def suma(n):
    return sum(range(1, n+1))

start = time.time()
res = suma(10)
end = time.time()
print(res)
print(f"Czas wykonania: {end - start} sekund")

"""1. napisz funkcje ktora przyjmuje parametr n i zlicza sume 1do n
2. zmierz czas wykonanie tej funkcji
"""